#include "MdColorScheme.h"

#include "MdDynamicColor.h"
#include "MdTokens.h"

namespace md {

namespace {

using R = ColorRole;

/// One `md.sys.color` role and the `md.ref.palette` tone it reads.
struct RoleMapping {
    R role;
    const char *reference; // md.ref.palette token name
};

// ---------------------------------------------------------------------------
// The six published baseline sets.
//
// These are NOT the output of the dynamic solver, and they must not be
// "reconciled" with it. `md.sys.color` is authored static data built on the M3
// reference palette: its primary family carries the seed's own chroma (so the
// default purple gives #6750a4 at tone 40), whereas a dynamic scheme solves
// tonal-spot at chroma 36 and yields #65558f for the same seed. Both are
// correct, in their own layer. See
// tests/TestMd3Contrast::dynamicTonalSpotIsNotTheStaticBaseline().
//
// Generated by tools/update-sys-color-fixtures.py --emit-cpp from
// material-web tokens/versions/latest/sass. Do not hand-edit: regenerate.
// ---------------------------------------------------------------------------

// clang-format off
// Baseline light — standard contrast — material-web tokens/versions/latest/sass
// (light-standard).
const RoleMapping kBaselineLight[] = {
    {R::Background,                "neutral98"},
    {R::Error,                     "error40"},
    {R::ErrorContainer,            "error90"},
    {R::InverseOnSurface,          "neutral95"},
    {R::InversePrimary,            "primary80"},
    {R::InverseSurface,            "neutral20"},
    {R::OnBackground,              "neutral10"},
    {R::OnError,                   "error100"},
    {R::OnErrorContainer,          "error30"},
    {R::OnPrimary,                 "primary100"},
    {R::OnPrimaryContainer,        "primary30"},
    {R::OnPrimaryFixed,            "primary10"},
    {R::OnPrimaryFixedVariant,     "primary30"},
    {R::OnSecondary,               "secondary100"},
    {R::OnSecondaryContainer,      "secondary30"},
    {R::OnSecondaryFixed,          "secondary10"},
    {R::OnSecondaryFixedVariant,   "secondary30"},
    {R::OnSurface,                 "neutral10"},
    {R::OnSurfaceVariant,          "neutral-variant30"},
    {R::OnTertiary,                "tertiary100"},
    {R::OnTertiaryContainer,       "tertiary30"},
    {R::OnTertiaryFixed,           "tertiary10"},
    {R::OnTertiaryFixedVariant,    "tertiary30"},
    {R::Outline,                   "neutral-variant50"},
    {R::OutlineVariant,            "neutral-variant80"},
    {R::Primary,                   "primary40"},
    {R::PrimaryContainer,          "primary90"},
    {R::PrimaryFixed,              "primary90"},
    {R::PrimaryFixedDim,           "primary80"},
    {R::Scrim,                     "neutral0"},
    {R::Secondary,                 "secondary40"},
    {R::SecondaryContainer,        "secondary90"},
    {R::SecondaryFixed,            "secondary90"},
    {R::SecondaryFixedDim,         "secondary80"},
    {R::Shadow,                    "neutral0"},
    {R::Surface,                   "neutral98"},
    {R::SurfaceBright,             "neutral98"},
    {R::SurfaceContainer,          "neutral94"},
    {R::SurfaceContainerHigh,      "neutral92"},
    {R::SurfaceContainerHighest,   "neutral90"},
    {R::SurfaceContainerLow,       "neutral96"},
    {R::SurfaceContainerLowest,    "neutral100"},
    {R::SurfaceDim,                "neutral87"},
    {R::SurfaceTint,               "primary40"},
    {R::SurfaceVariant,            "neutral-variant90"},
    {R::Tertiary,                  "tertiary40"},
    {R::TertiaryContainer,         "tertiary90"},
    {R::TertiaryFixed,             "tertiary90"},
    {R::TertiaryFixedDim,          "tertiary80"},
};

// Baseline light — medium contrast — material-web tokens/versions/latest/sass
// (light-medium).
const RoleMapping kBaselineLightMedium[] = {
    {R::Background,                "neutral98"},
    {R::Error,                     "error30"},
    {R::ErrorContainer,            "error40"},
    {R::InverseOnSurface,          "neutral100"},
    {R::InversePrimary,            "primary80"},
    {R::InverseSurface,            "neutral20"},
    {R::OnBackground,              "neutral0"},
    {R::OnError,                   "error100"},
    {R::OnErrorContainer,          "error100"},
    {R::OnPrimary,                 "primary100"},
    {R::OnPrimaryContainer,        "primary100"},
    {R::OnPrimaryFixed,            "primary100"},
    {R::OnPrimaryFixedVariant,     "primary100"},
    {R::OnSecondary,               "secondary100"},
    {R::OnSecondaryContainer,      "secondary100"},
    {R::OnSecondaryFixed,          "secondary100"},
    {R::OnSecondaryFixedVariant,   "secondary100"},
    {R::OnSurface,                 "neutral0"},
    {R::OnSurfaceVariant,          "neutral-variant20"},
    {R::OnTertiary,                "tertiary100"},
    {R::OnTertiaryContainer,       "tertiary100"},
    {R::OnTertiaryFixed,           "tertiary100"},
    {R::OnTertiaryFixedVariant,    "tertiary100"},
    {R::Outline,                   "neutral-variant30"},
    {R::OutlineVariant,            "neutral-variant50"},
    {R::Primary,                   "primary30"},
    {R::PrimaryContainer,          "primary40"},
    {R::PrimaryFixed,              "primary40"},
    {R::PrimaryFixedDim,           "primary30"},
    {R::Scrim,                     "neutral0"},
    {R::Secondary,                 "secondary30"},
    {R::SecondaryContainer,        "secondary40"},
    {R::SecondaryFixed,            "secondary40"},
    {R::SecondaryFixedDim,         "secondary30"},
    {R::Shadow,                    "neutral0"},
    {R::Surface,                   "neutral98"},
    {R::SurfaceBright,             "neutral98"},
    {R::SurfaceContainer,          "neutral94"},
    {R::SurfaceContainerHigh,      "neutral92"},
    {R::SurfaceContainerHighest,   "neutral90"},
    {R::SurfaceContainerLow,       "neutral96"},
    {R::SurfaceContainerLowest,    "neutral100"},
    {R::SurfaceDim,                "neutral87"},
    {R::SurfaceTint,               "primary30"},
    {R::SurfaceVariant,            "neutral-variant90"},
    {R::Tertiary,                  "tertiary30"},
    {R::TertiaryContainer,         "tertiary40"},
    {R::TertiaryFixed,             "tertiary40"},
    {R::TertiaryFixedDim,          "tertiary30"},
};

// Baseline light — high contrast — material-web tokens/versions/latest/sass
// (light-high).
const RoleMapping kBaselineLightHigh[] = {
    {R::Background,                "neutral98"},
    {R::Error,                     "error20"},
    {R::ErrorContainer,            "error30"},
    {R::InverseOnSurface,          "neutral100"},
    {R::InversePrimary,            "primary80"},
    {R::InverseSurface,            "neutral20"},
    {R::OnBackground,              "neutral0"},
    {R::OnError,                   "error100"},
    {R::OnErrorContainer,          "error100"},
    {R::OnPrimary,                 "primary100"},
    {R::OnPrimaryContainer,        "primary100"},
    {R::OnPrimaryFixed,            "primary100"},
    {R::OnPrimaryFixedVariant,     "primary100"},
    {R::OnSecondary,               "secondary100"},
    {R::OnSecondaryContainer,      "secondary100"},
    {R::OnSecondaryFixed,          "secondary100"},
    {R::OnSecondaryFixedVariant,   "secondary100"},
    {R::OnSurface,                 "neutral0"},
    {R::OnSurfaceVariant,          "neutral-variant0"},
    {R::OnTertiary,                "tertiary100"},
    {R::OnTertiaryContainer,       "tertiary100"},
    {R::OnTertiaryFixed,           "tertiary100"},
    {R::OnTertiaryFixedVariant,    "tertiary100"},
    {R::Outline,                   "neutral-variant20"},
    {R::OutlineVariant,            "neutral-variant30"},
    {R::Primary,                   "primary20"},
    {R::PrimaryContainer,          "primary30"},
    {R::PrimaryFixed,              "primary30"},
    {R::PrimaryFixedDim,           "primary20"},
    {R::Scrim,                     "neutral0"},
    {R::Secondary,                 "secondary20"},
    {R::SecondaryContainer,        "secondary30"},
    {R::SecondaryFixed,            "secondary30"},
    {R::SecondaryFixedDim,         "secondary20"},
    {R::Shadow,                    "neutral0"},
    {R::Surface,                   "neutral98"},
    {R::SurfaceBright,             "neutral98"},
    {R::SurfaceContainer,          "neutral94"},
    {R::SurfaceContainerHigh,      "neutral92"},
    {R::SurfaceContainerHighest,   "neutral90"},
    {R::SurfaceContainerLow,       "neutral96"},
    {R::SurfaceContainerLowest,    "neutral100"},
    {R::SurfaceDim,                "neutral87"},
    {R::SurfaceTint,               "primary20"},
    {R::SurfaceVariant,            "neutral-variant90"},
    {R::Tertiary,                  "tertiary20"},
    {R::TertiaryContainer,         "tertiary30"},
    {R::TertiaryFixed,             "tertiary30"},
    {R::TertiaryFixedDim,          "tertiary20"},
};

// Baseline dark — standard contrast — material-web tokens/versions/latest/sass
// (dark-standard).
const RoleMapping kBaselineDark[] = {
    {R::Background,                "neutral6"},
    {R::Error,                     "error80"},
    {R::ErrorContainer,            "error30"},
    {R::InverseOnSurface,          "neutral20"},
    {R::InversePrimary,            "primary40"},
    {R::InverseSurface,            "neutral90"},
    {R::OnBackground,              "neutral90"},
    {R::OnError,                   "error20"},
    {R::OnErrorContainer,          "error90"},
    {R::OnPrimary,                 "primary20"},
    {R::OnPrimaryContainer,        "primary90"},
    {R::OnPrimaryFixed,            "primary10"},
    {R::OnPrimaryFixedVariant,     "primary30"},
    {R::OnSecondary,               "secondary20"},
    {R::OnSecondaryContainer,      "secondary90"},
    {R::OnSecondaryFixed,          "secondary10"},
    {R::OnSecondaryFixedVariant,   "secondary30"},
    {R::OnSurface,                 "neutral90"},
    {R::OnSurfaceVariant,          "neutral-variant80"},
    {R::OnTertiary,                "tertiary20"},
    {R::OnTertiaryContainer,       "tertiary90"},
    {R::OnTertiaryFixed,           "tertiary10"},
    {R::OnTertiaryFixedVariant,    "tertiary30"},
    {R::Outline,                   "neutral-variant60"},
    {R::OutlineVariant,            "neutral-variant30"},
    {R::Primary,                   "primary80"},
    {R::PrimaryContainer,          "primary30"},
    {R::PrimaryFixed,              "primary90"},
    {R::PrimaryFixedDim,           "primary80"},
    {R::Scrim,                     "neutral0"},
    {R::Secondary,                 "secondary80"},
    {R::SecondaryContainer,        "secondary30"},
    {R::SecondaryFixed,            "secondary90"},
    {R::SecondaryFixedDim,         "secondary80"},
    {R::Shadow,                    "neutral0"},
    {R::Surface,                   "neutral6"},
    {R::SurfaceBright,             "neutral24"},
    {R::SurfaceContainer,          "neutral12"},
    {R::SurfaceContainerHigh,      "neutral17"},
    {R::SurfaceContainerHighest,   "neutral22"},
    {R::SurfaceContainerLow,       "neutral10"},
    {R::SurfaceContainerLowest,    "neutral4"},
    {R::SurfaceDim,                "neutral6"},
    {R::SurfaceTint,               "primary80"},
    {R::SurfaceVariant,            "neutral-variant30"},
    {R::Tertiary,                  "tertiary80"},
    {R::TertiaryContainer,         "tertiary30"},
    {R::TertiaryFixed,             "tertiary90"},
    {R::TertiaryFixedDim,          "tertiary80"},
};

// Baseline dark — medium contrast — material-web tokens/versions/latest/sass
// (dark-medium).
const RoleMapping kBaselineDarkMedium[] = {
    {R::Background,                "neutral6"},
    {R::Error,                     "error90"},
    {R::ErrorContainer,            "error60"},
    {R::InverseOnSurface,          "neutral10"},
    {R::InversePrimary,            "primary30"},
    {R::InverseSurface,            "neutral90"},
    {R::OnBackground,              "neutral100"},
    {R::OnError,                   "error10"},
    {R::OnErrorContainer,          "error0"},
    {R::OnPrimary,                 "primary10"},
    {R::OnPrimaryContainer,        "primary0"},
    {R::OnPrimaryFixed,            "primary0"},
    {R::OnPrimaryFixedVariant,     "primary20"},
    {R::OnSecondary,               "secondary10"},
    {R::OnSecondaryContainer,      "secondary0"},
    {R::OnSecondaryFixed,          "secondary0"},
    {R::OnSecondaryFixedVariant,   "secondary20"},
    {R::OnSurface,                 "neutral100"},
    {R::OnSurfaceVariant,          "neutral-variant90"},
    {R::OnTertiary,                "tertiary10"},
    {R::OnTertiaryContainer,       "tertiary0"},
    {R::OnTertiaryFixed,           "tertiary0"},
    {R::OnTertiaryFixedVariant,    "tertiary20"},
    {R::Outline,                   "neutral-variant70"},
    {R::OutlineVariant,            "neutral-variant60"},
    {R::Primary,                   "primary90"},
    {R::PrimaryContainer,          "primary60"},
    {R::PrimaryFixed,              "primary90"},
    {R::PrimaryFixedDim,           "primary80"},
    {R::Scrim,                     "neutral0"},
    {R::Secondary,                 "secondary90"},
    {R::SecondaryContainer,        "secondary60"},
    {R::SecondaryFixed,            "secondary90"},
    {R::SecondaryFixedDim,         "secondary80"},
    {R::Shadow,                    "neutral0"},
    {R::Surface,                   "neutral6"},
    {R::SurfaceBright,             "neutral24"},
    {R::SurfaceContainer,          "neutral12"},
    {R::SurfaceContainerHigh,      "neutral17"},
    {R::SurfaceContainerHighest,   "neutral22"},
    {R::SurfaceContainerLow,       "neutral10"},
    {R::SurfaceContainerLowest,    "neutral4"},
    {R::SurfaceDim,                "neutral6"},
    {R::SurfaceTint,               "primary90"},
    {R::SurfaceVariant,            "neutral-variant30"},
    {R::Tertiary,                  "tertiary90"},
    {R::TertiaryContainer,         "tertiary60"},
    {R::TertiaryFixed,             "tertiary90"},
    {R::TertiaryFixedDim,          "tertiary80"},
};

// Baseline dark — high contrast — material-web tokens/versions/latest/sass
// (dark-high).
const RoleMapping kBaselineDarkHigh[] = {
    {R::Background,                "neutral6"},
    {R::Error,                     "error95"},
    {R::ErrorContainer,            "error80"},
    {R::InverseOnSurface,          "neutral0"},
    {R::InversePrimary,            "primary20"},
    {R::InverseSurface,            "neutral90"},
    {R::OnBackground,              "neutral100"},
    {R::OnError,                   "error0"},
    {R::OnErrorContainer,          "error0"},
    {R::OnPrimary,                 "primary0"},
    {R::OnPrimaryContainer,        "primary0"},
    {R::OnPrimaryFixed,            "primary0"},
    {R::OnPrimaryFixedVariant,     "primary0"},
    {R::OnSecondary,               "secondary0"},
    {R::OnSecondaryContainer,      "secondary0"},
    {R::OnSecondaryFixed,          "secondary0"},
    {R::OnSecondaryFixedVariant,   "secondary0"},
    {R::OnSurface,                 "neutral100"},
    {R::OnSurfaceVariant,          "neutral-variant100"},
    {R::OnTertiary,                "tertiary0"},
    {R::OnTertiaryContainer,       "tertiary0"},
    {R::OnTertiaryFixed,           "tertiary0"},
    {R::OnTertiaryFixedVariant,    "tertiary0"},
    {R::Outline,                   "neutral-variant95"},
    {R::OutlineVariant,            "neutral-variant80"},
    {R::Primary,                   "primary95"},
    {R::PrimaryContainer,          "primary80"},
    {R::PrimaryFixed,              "primary90"},
    {R::PrimaryFixedDim,           "primary80"},
    {R::Scrim,                     "neutral0"},
    {R::Secondary,                 "secondary95"},
    {R::SecondaryContainer,        "secondary80"},
    {R::SecondaryFixed,            "secondary90"},
    {R::SecondaryFixedDim,         "secondary80"},
    {R::Shadow,                    "neutral0"},
    {R::Surface,                   "neutral6"},
    {R::SurfaceBright,             "neutral24"},
    {R::SurfaceContainer,          "neutral12"},
    {R::SurfaceContainerHigh,      "neutral17"},
    {R::SurfaceContainerHighest,   "neutral22"},
    {R::SurfaceContainerLow,       "neutral10"},
    {R::SurfaceContainerLowest,    "neutral4"},
    {R::SurfaceDim,                "neutral6"},
    {R::SurfaceTint,               "primary95"},
    {R::SurfaceVariant,            "neutral-variant30"},
    {R::Tertiary,                  "tertiary95"},
    {R::TertiaryContainer,         "tertiary80"},
    {R::TertiaryFixed,             "tertiary90"},
    {R::TertiaryFixedDim,          "tertiary80"},
};
// clang-format on

/// Baseline table for a mode and contrast level. Every (mode, level) pair has
/// its own published set, so there is nothing to derive or interpolate here.
const RoleMapping *baselineTable(ThemeMode mode, ContrastLevel level, int *count)
{
    struct Entry {
        ThemeMode mode;
        ContrastLevel level;
        const RoleMapping *table;
        int count;
    };
    static const Entry kEntries[] = {
        {ThemeMode::Light, ContrastLevel::Standard, kBaselineLight,
         int(sizeof(kBaselineLight) / sizeof(kBaselineLight[0]))},
        {ThemeMode::Light, ContrastLevel::Medium, kBaselineLightMedium,
         int(sizeof(kBaselineLightMedium) / sizeof(kBaselineLightMedium[0]))},
        {ThemeMode::Light, ContrastLevel::High, kBaselineLightHigh,
         int(sizeof(kBaselineLightHigh) / sizeof(kBaselineLightHigh[0]))},
        {ThemeMode::Dark, ContrastLevel::Standard, kBaselineDark,
         int(sizeof(kBaselineDark) / sizeof(kBaselineDark[0]))},
        {ThemeMode::Dark, ContrastLevel::Medium, kBaselineDarkMedium,
         int(sizeof(kBaselineDarkMedium) / sizeof(kBaselineDarkMedium[0]))},
        {ThemeMode::Dark, ContrastLevel::High, kBaselineDarkHigh,
         int(sizeof(kBaselineDarkHigh) / sizeof(kBaselineDarkHigh[0]))},
    };

    for (const Entry &entry : kEntries) {
        if (entry.mode == mode && entry.level == level) {
            *count = entry.count;
            return entry.table;
        }
    }

    // No published reduced-contrast set exists. Reduced is a *dynamic* level
    // (material-color-utilities' contrastLevel -1.0), so the baseline falls
    // back to the standard set rather than inventing tones.
    *count = int(sizeof(kBaselineLight) / sizeof(kBaselineLight[0]));
    return mode == ThemeMode::Dark ? kBaselineDark : kBaselineLight;
}

} // namespace

MdColorScheme::MdColorScheme() = default;

MdColorScheme MdColorScheme::baseline(ThemeMode mode, ContrastLevel level)
{
    MdColorScheme scheme;
    scheme.m_mode = mode;
    scheme.m_dynamic = false;
    scheme.m_contrast = level;

    int count = 0;
    const RoleMapping *table = baselineTable(mode, level, &count);
    for (int i = 0; i < count; ++i) {
        scheme.m_colors.insert(table[i].role,
                               MdReferenceTokens::referenceColor(
                                   QString::fromUtf8(table[i].reference)));
    }
    return scheme;
}

MdColorScheme MdColorScheme::dynamic(const QColor &seed,
                                     ThemeMode mode,
                                     SchemeVariant variant,
                                     ContrastLevel contrast)
{
    const Argb seedArgb = MdColorMath::argbFromHex(seed.name(QColor::HexRgb));
    const MdDynamicScheme dynamicScheme = MdDynamicScheme::create(seedArgb, mode, variant, contrast);

    MdColorScheme scheme;
    scheme.m_mode = mode;
    scheme.m_dynamic = true;
    scheme.m_variant = variant;
    scheme.m_contrast = contrast;
    scheme.m_seed = seed;
    for (int i = 0; i < int(ColorRole::Count); ++i) {
        const ColorRole role = static_cast<ColorRole>(i);
        scheme.m_colors.insert(role, QColor::fromRgba(QRgb(dynamicScheme.color(role))));
    }
    return scheme;
}

QColor MdColorScheme::color(ColorRole role) const
{
    return m_colors.value(role);
}

void MdColorScheme::setColor(ColorRole role, const QColor &color)
{
    m_colors.insert(role, color);
}

QString MdColorScheme::hex(ColorRole role) const
{
    const QColor value = color(role);
    return value.isValid() ? value.name(QColor::HexRgb) : QStringLiteral("#000000");
}

} // namespace md
